[package]
name = "sqframe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.2.1"
clap = { version = "4.4.7", features = ["derive"] }
fastblur = "0.1.1"
image = "0.24.7"
